name: Build
on:
  workflow_dispatch

jobs:
  prepare:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-python@v4
      with: 
       python-version: '3.10'
       
  build_linux:
    needs: prepare
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Requirements
        run: |
            sudo apt-get -y install zip pandoc man sed
            python -m pip install -U pip setuptools wheel twine
            python -m pip install -U Pyinstaller -r requirements.txt
            
      - name: Actually build
        shell: bash -l {0}
        run: |
          python pyinst.py --onedir
          python build.py
